<a href="https://colab.research.google.com/github/arhamkac/Regression-Arham/blob/tts/Train_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
wines=pd.read_csv("wines_SPA.csv")
wines.head()

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
0,Teso La Monja,Tinto,2013,4.9,58,Espana,Toro,995.00,Toro Red,5.0,3.0
1,Artadi,Vina El Pison,2018,4.9,31,Espana,Vino de Espana,313.50,Tempranillo,4.0,2.0
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0

In [5]:
wines.isna().sum()

winery            0
wine              0
year              2
rating            0
num_reviews       0
country           0
region            0
price             0
type            545
body           1169
acidity        1169
dtype: int64

In [6]:
wines.drop('year',axis='columns',inplace=True)

In [7]:
wines['body'].fillna(wines['body'].median(),inplace=True)
wines['acidity'].fillna(wines['acidity'].median(),inplace=True)

<ipython-input-7-4af65bf4e1f9>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  wines['body'].fillna(wines['body'].median(),inplace=True)
<ipython-input-7-4af65bf4e1f9>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  wines['acidity'].fillna(wines['acidity'].median(),inplace=True)

In [8]:
wines.drop('type',axis='columns',inplace=True)

In [9]:
Q1 = wines['num_reviews'].quantile(0.25)
Q3 = wines['num_reviews'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
wines_f = wines[(wines['num_reviews'] > lower_bound) & (wines['num_reviews'] < upper_bound)]

In [10]:
#Converting datatype to all num
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
wines_f['winery']=le.fit_transform(wines_f['winery'])
wines_f['wine']=le.fit_transform(wines_f['wine'])
wines_f['country']=le.fit_transform(wines_f['country'])
wines_f['region']=le.fit_transform(wines_f['region'])

<ipython-input-10-c82d646297f5>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wines_f['winery']=le.fit_transform(wines_f['winery'])
<ipython-input-10-c82d646297f5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wines_f['wine']=le.fit_transform(wines_f['wine'])
<ipython-input-10-c82d646297f5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wines_f['country']=le.fit_transform(wines_f['country'])
<ipython-input-10-c82d646297f5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wines_f['region']=le.fit_transform(wines_f['region'])

In [11]:
wines_f.head()

    winery  wine  rating  num_reviews  country  region   price  body  acidity
12      74    83     4.8          438        0      19  430.00   5.0      3.0
13      74    82     4.8          417        0      19  925.00   5.0      3.0
14      72    20     4.8          398        0      14  350.00   5.0      1.0
15      57    17     4.8          372        0      19  166.18   5.0      3.0
72      74    83     4.7          442        0      19  290.00   5.0      3.0

In [12]:
#Train Test Split Functionality
x=wines_f.drop('price',axis='columns')
y=wines_f['price']
def train_test_split(x,y,test_size=0.2):
    #Shuffled using random.shuffle method in numpy by first changing the indexing
    #of elements and then locating them with their indexes
    index=np.arange(len(x))
    np.random.shuffle(index)
    x=x.iloc[index]
    y=y.iloc[index]
    split_size=int(len(x)*(1-test_size))
    x_train=x[:split_size]
    x_test=x[split_size:]
    y_train=y[:split_size]
    y_test=y[split_size:]
    return x_train,x_test,y_train,y_test

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [14]:
x_train.shape

(4183, 8)

In [15]:
x_test.shape

(1395, 8)